GET localhost:3000/contacts
//to get all contacts

GET localhost:3000/contacts?id=1
//get contact by id

GET localhost:3000/contacts?firstName=Scott
//get contact by first name

GET localhost:3000/contacts?lastName=Iverson
//get contact by last name

GET localhost:3000/contacts?favoriteColor=Pink
//get contact by favorite color

POST localhost:3000/addContact?favoriteColor=Blue&firstName=John&lastName=Smith&birthday=April 1, 2010&email=john@nowhere.com&id=5
//add contact

PUT localhost:3000/updateContact?id=5&firstName=James&lastName=Smith&favoriteColor=Green
//update contact

DELETE localhost:3000/deleteContact?id=4
//delete contact

GET http://localhost:3000/api-docs/
//swagger api docs